RIVETBUILD := RIVET_BUILD_BEFORE_INSTALL=1 bash $(top_builddir)/bin/rivet-build

%.so:
	@+echo && $(RIVETBUILD) $@ $^ -I$(top_builddir)/include

RivetLWTNN.so: EXAMPLE_LWTNN.cc
	@+echo && $(RIVETBUILD) $@ $^ -I$(top_builddir)/include -I$(LWTNN_PREFIX)/include -L$(LWTNN_PREFIX)/lib -llwtnn
