#! /usr/bin/env python3

from matplotlib import pyplot as plt
plt.figure()
with open("labels.dat") as f:
    #print(len(f))
    for i, line in enumerate(f):
        tex = line.strip()
        print(f"{i}: rendering '{tex}'")
        plt.text(0.0, 0.0, tex)
        plt.savefig("labels.pdf")
        plt.cla()
