#! /usr/bin/env bash
RUNNING=(alice atlas cms lhcb totem lhcf star phenix cleo h1 zeus hermes babar belle opal delphi aleph l3  sld compass snd cmd bes besiii cdf d0 kloe)
PRE_2000=(amy jade argus tasso venus topaz pluto hrs mac marki markii markj tpc dm1 dm2 cello fenice lena mupi cusb dasp desy147 e735 olya)
SMALL=(amy jade argus snd cmd topaz pluto tasso dm1 dm2 lhcf cello mupi lena kloe fenice bbar brahms kloe cusb dasp desy147 e735 ehs two_gamma hrs mac marki markii markj md1 nd nmd olya sfm totem tpc venus fenice)
OLD=(dasp desy147 dm1 two_gamma jade marki markii markj mupi nmd pluto tasso)
EXPTS=("${RUNNING[@]}" "${PRE_2000[@]}")


for EXPT in ${EXPTS[@]}; do
    # set the number of authors (needs to be lower for small experiments
    NAUTH=100
    for SMALLEXPT in ${SMALL[@]}; do
	if [[ "$SMALLEXPT" == "$EXPT" ]]; then
	    NAUTH=15
	    break
	fi
    done
    # change start year for older experiments
    STARTYEAR=1980
    ENDYEAR=$(date +"%Y")
    for OLDEXPT in ${PRE_2000[@]}; do
	if [[ "$OLDEXPT" == "$EXPT" ]]; then
	    ENDYEAR=2000
	    break
	fi
    done
    for OLDEXPT in ${OLD[@]}; do
	if [[ "$OLDEXPT" == "$EXPT" ]]; then
	    STARTYEAR=1970
	    ENDYEAR=1990
	    break
	fi
    done
    for YEAR in $(seq $STARTYEAR $ENDYEAR); do
        OUT=inspire-$EXPT-$YEAR.marc.xml
        if [[ -e $OUT ]]; then
            echo "$OUT exists: skipping $EXPT $YEAR download"
        else
            echo "Downloading $EXPT $YEAR Inspire record to $OUT"
            #URL="https://cds.cern.ch/search?ln=en&cc=${COLL}&op1=a&m1=a&p1=${YEAR}&f1=year&rg=200&jrec=1&of=xm"
            #URL="https://inspirehep.net/search?ln=en&ln=en&p=find+cn+${EXPT}+and+ac+100%2B+and+de+${YEAR}&of=xm&action_search=Search&sf=earliestdate&so=d&rm=&rg=250&sc=0&ot=001,024,035,037,710,245"
	        URL="https://old.inspirehep.net/search?ln=en&ln=en&p=find+cn+${EXPT}+and+ac+${NAUTH}%2B+and+de+${YEAR}&of=xm&action_search=Search&sf=earliestdate&so=d&rm=&rg=250&sc=0&ot=001,024,035,037,710,245"
            echo "$URL"
            wget "$URL" -O $OUT
        fi
    done
done
