name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:

  compilejobOSX:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: macos-latest
    name: Rivet_on_OSX
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint.sh
