FROM hepstore/rivet:3.1.1
MAINTAINER Andy Buckley <andy.buckley@cern.ch>

WORKDIR /work

RUN wget https://launchpad.net/mg5amcnlo/2.0/2.7.x/+download/MG5_aMC_v2.7.2.tar.gz -O- | tar xz

WORKDIR /work
